spring.application.name=springsecurityjwt
#spring.security.user.name=tester
#spring.security.user.password=testing

spring.datasource.url=jdbc:mysql://localhost:3306/sessiondb
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
